version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    image: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      custom-net:
        aliases:
          - landing
  addition-service:
    build : ./landing/add
    image : addition-service
    ports:
      - 5051:5051  # host:container
    networks:
      custom-net:
        aliases:
          - add
  # Add more services below      
  subtraction-service:
    build : ./landing/sub
    image : subtraction-service
    ports:
      - 5052:5052  # host:container
    networks:
      custom-net:
        aliases:
          - sub
  multiplication-service:
    build : ./landing/mul
    image : multiplication-service
    ports:
      - 5053:5053  # host:container
    networks:
      custom-net:
        aliases:
          - mul
  division-service:
    build : ./landing/div
    image : division-service
    ports:
      - 5054:5054  # host:container
    networks:
      custom-net:
        aliases:
          - div
  modulo-service:
    build : ./landing/mod
    image : modulo-service
    ports:
      - 5055:5055  # host:container
    networks:
      custom-net:
        aliases:
          - mod
  greater-than-service:
    build : ./landing/gt
    image : greater-than-service
    ports:
      - 5056:5056  # host:container
    networks:
      custom-net:
        aliases:
          - gt
  less-than-service:
    build : ./landing/lt
    image : less-than-service
    ports:
      - 5057:5057  # host:container
    networks:
      custom-net:
        aliases:
          - lt
  newadd-service:
    build: ./landing/newAdd  # path is relative to docker-compose.yml location
    image: newadd-service
    ports:
      - 5060:5060  # host:container
    networks:
      custom-net:
        aliases:
          - newadd
  lcm-service:
    build: ./landing/lcm  # path is relative to docker-compose.yml location
    image: lcm-service
    ports:
      - 5061:5061  # host:container
    networks:
      custom-net:
        aliases:
          - lcm
networks:
  custom-net:
